"""Unit tests for eero.cli.output module.

Tests cover:
- OutputFormat and DetailLevel enums
- OutputMeta and OutputContext dataclasses
- OutputRenderer class methods
- OutputManager class methods
"""

import json
from io import StringIO
from unittest.mock import MagicMock

import pytest
from rich.console import Console

from eeroctl.output import (
    CLIENT_TABLE_COLUMNS,
    EERO_TABLE_COLUMNS,
    NETWORK_TABLE_COLUMNS,
    PROFILE_TABLE_COLUMNS,
    DetailLevel,
    OutputContext,
    OutputFormat,
    OutputManager,
    OutputMeta,
    OutputRenderer,
    get_renderer,
)

# ========================== Enum Tests ==========================


class TestOutputFormat:
    """Tests for OutputFormat enum."""

    def test_table_value(self):
        """Test TABLE format value."""
        assert OutputFormat.TABLE == "table"

    def test_list_value(self):
        """Test LIST format value."""
        assert OutputFormat.LIST == "list"

    def test_json_value(self):
        """Test JSON format value."""
        assert OutputFormat.JSON == "json"

    def test_all_formats_are_strings(self):
        """Test all formats are string enums."""
        for fmt in OutputFormat:
            assert isinstance(fmt.value, str)


class TestDetailLevel:
    """Tests for DetailLevel enum."""

    def test_brief_value(self):
        """Test BRIEF level value."""
        assert DetailLevel.BRIEF == "brief"

    def test_full_value(self):
        """Test FULL level value."""
        assert DetailLevel.FULL == "full"


# ========================== OutputMeta Tests ==========================


class TestOutputMeta:
    """Tests for OutputMeta dataclass."""

    def test_default_timestamp_generated(self):
        """Test timestamp is generated by default."""
        meta = OutputMeta()

        assert meta.timestamp is not None
        assert "T" in meta.timestamp  # ISO format
        assert meta.timestamp.endswith("Z")  # UTC

    def test_default_values(self):
        """Test default values."""
        meta = OutputMeta()

        assert meta.network_id is None
        assert meta.warnings == []

    def test_custom_values(self):
        """Test custom values."""
        meta = OutputMeta(
            timestamp="2025-01-07T12:00:00Z",
            network_id="net_123",
            warnings=["Warning 1"],
        )

        assert meta.timestamp == "2025-01-07T12:00:00Z"
        assert meta.network_id == "net_123"
        assert meta.warnings == ["Warning 1"]


# ========================== OutputContext Tests ==========================


class TestOutputContext:
    """Tests for OutputContext dataclass."""

    def test_default_values(self):
        """Test default values."""
        ctx = OutputContext()

        assert ctx.format == OutputFormat.TABLE
        assert ctx.detail == DetailLevel.BRIEF
        assert ctx.quiet is False
        assert ctx.no_color is False
        assert ctx.network_id is None

    def test_custom_values(self):
        """Test custom values."""
        ctx = OutputContext(
            format=OutputFormat.JSON,
            detail=DetailLevel.FULL,
            quiet=True,
            no_color=True,
            network_id="net_abc",
        )

        assert ctx.format == OutputFormat.JSON
        assert ctx.detail == DetailLevel.FULL
        assert ctx.quiet is True
        assert ctx.no_color is True
        assert ctx.network_id == "net_abc"

    def test_console_property_creates_instance(self):
        """Test console property creates Console on first access."""
        ctx = OutputContext()

        console = ctx.console
        assert console is not None
        assert isinstance(console, Console)

        # Should return same instance
        assert ctx.console is console

    def test_err_console_property_creates_instance(self):
        """Test err_console property creates Console for stderr."""
        ctx = OutputContext()

        err_console = ctx.err_console
        assert err_console is not None
        assert isinstance(err_console, Console)


# ========================== OutputRenderer Tests ==========================


class TestOutputRenderer:
    """Tests for OutputRenderer class."""

    @pytest.fixture
    def renderer(self) -> OutputRenderer:
        """Create a renderer with captured output."""
        ctx = OutputContext(format=OutputFormat.TABLE)
        return OutputRenderer(ctx)

    @pytest.fixture
    def json_renderer(self) -> OutputRenderer:
        """Create a JSON renderer."""
        ctx = OutputContext(format=OutputFormat.JSON)
        return OutputRenderer(ctx)

    def test_render_json_structure(self, json_renderer):
        """Test render_json produces correct envelope structure."""
        # Capture output
        output = StringIO()
        json_renderer.ctx._console = Console(file=output, force_terminal=False)

        json_renderer.render_json(
            data={"key": "value"},
            schema="eero.test/v1",
        )

        result = json.loads(output.getvalue())

        assert "schema" in result
        assert result["schema"] == "eero.test/v1"
        assert "data" in result
        assert result["data"] == {"key": "value"}
        assert "meta" in result
        assert "timestamp" in result["meta"]

    def test_render_json_with_meta(self, json_renderer):
        """Test render_json includes custom metadata."""
        output = StringIO()
        json_renderer.ctx._console = Console(file=output, force_terminal=False)

        meta = OutputMeta(
            timestamp="2025-01-07T00:00:00Z",
            network_id="net_test",
            warnings=["Test warning"],
        )

        json_renderer.render_json(
            data=[1, 2, 3],
            schema="eero.list/v1",
            meta=meta,
        )

        result = json.loads(output.getvalue())

        assert result["meta"]["timestamp"] == "2025-01-07T00:00:00Z"
        assert result["meta"]["network_id"] == "net_test"
        assert result["meta"]["warnings"] == ["Test warning"]

    def test_render_mutation_result_json(self, json_renderer):
        """Test render_mutation_result in JSON mode."""
        output = StringIO()
        json_renderer.ctx._console = Console(file=output, force_terminal=False)

        json_renderer.render_mutation_result(
            changed=True,
            target="eero_123",
            action="reboot",
            job_id="job_456",
        )

        result = json.loads(output.getvalue())

        assert result["data"]["changed"] is True
        assert result["data"]["target"] == "eero_123"
        assert result["data"]["action"] == "reboot"
        assert result["data"]["job_id"] == "job_456"

    def test_render_mutation_result_table(self, renderer):
        """Test render_mutation_result in table mode."""
        output = StringIO()
        renderer.ctx._console = Console(file=output, force_terminal=False)

        renderer.render_mutation_result(
            changed=True,
            target="Living Room",
            action="reboot",
        )

        text = output.getvalue()
        # Should contain success indicator and action info
        assert "reboot" in text or "Living Room" in text

    def test_render_table(self, renderer):
        """Test render_table produces table output."""
        output = StringIO()
        renderer.ctx._console = Console(file=output, force_terminal=False, width=120)

        renderer.render_table(
            title="Test Table",
            columns=[
                {"name": "ID", "style": "dim"},
                {"name": "Name", "style": "cyan"},
            ],
            rows=[
                ["1", "First"],
                ["2", "Second"],
            ],
        )

        text = output.getvalue()
        assert "Test Table" in text
        assert "ID" in text
        assert "Name" in text

    def test_render_list(self, renderer):
        """Test render_list outputs one item per line."""
        output = StringIO()
        renderer.ctx._console = Console(file=output, force_terminal=False)

        renderer.render_list(["item1", "item2", "item3"])

        lines = output.getvalue().strip().split("\n")
        assert len(lines) == 3
        assert "item1" in lines[0]
        assert "item2" in lines[1]
        assert "item3" in lines[2]

    def test_render_panel(self, renderer):
        """Test render_panel creates bordered output."""
        output = StringIO()
        renderer.ctx._console = Console(file=output, force_terminal=False, width=80)

        renderer.render_panel(
            content="Panel content here",
            title="Panel Title",
            border_style="blue",
        )

        text = output.getvalue()
        assert "Panel Title" in text
        assert "Panel content" in text

    def test_render_error(self, renderer):
        """Test render_error outputs to stderr console."""
        output = StringIO()
        renderer.ctx._err_console = Console(file=output, force_terminal=False)

        renderer.render_error("Something went wrong")

        text = output.getvalue()
        assert "Error" in text
        assert "Something went wrong" in text

    def test_render_error_with_hint(self, renderer):
        """Test render_error includes hint when provided."""
        output = StringIO()
        renderer.ctx._err_console = Console(file=output, force_terminal=False)

        renderer.render_error("Auth failed", hint="Run 'eero auth login'")

        text = output.getvalue()
        assert "Auth failed" in text
        assert "Hint" in text
        assert "eero auth login" in text

    def test_render_warning(self, renderer):
        """Test render_warning outputs warning message."""
        output = StringIO()
        renderer.ctx._err_console = Console(file=output, force_terminal=False)

        renderer.render_warning("Something might be wrong")

        text = output.getvalue()
        assert "Warning" in text
        assert "Something might be wrong" in text

    def test_render_success(self, renderer):
        """Test render_success outputs success message."""
        output = StringIO()
        renderer.ctx._console = Console(file=output, force_terminal=False)

        renderer.render_success("Operation completed")

        text = output.getvalue()
        assert "Operation completed" in text

    def test_render_success_quiet_mode(self):
        """Test render_success suppressed in quiet mode."""
        ctx = OutputContext(quiet=True)
        renderer = OutputRenderer(ctx)
        output = StringIO()
        renderer.ctx._console = Console(file=output, force_terminal=False)

        renderer.render_success("Should not appear")

        assert output.getvalue() == ""

    def test_render_info(self, renderer):
        """Test render_info outputs info message."""
        output = StringIO()
        renderer.ctx._console = Console(file=output, force_terminal=False)

        renderer.render_info("Information message")

        text = output.getvalue()
        assert "Information message" in text


# ========================== OutputManager Tests ==========================


class TestOutputManager:
    """Tests for OutputManager class."""

    @pytest.fixture
    def manager(self) -> OutputManager:
        """Create an OutputManager with captured output."""
        output = StringIO()
        console = Console(file=output, force_terminal=False, width=120)
        return OutputManager(console)

    def test_render_json_format(self, manager):
        """Test render in JSON format."""
        output = StringIO()
        manager.console = Console(file=output, force_terminal=False)

        manager.render(
            format="json",
            data={"id": "123", "name": "Test"},
            schema="eero.test/v1",
            meta={},
        )

        result = json.loads(output.getvalue())
        assert result["schema"] == "eero.test/v1"
        assert result["data"]["id"] == "123"

    def test_render_list_format(self, manager):
        """Test render in list format."""
        output = StringIO()
        manager.console = Console(file=output, force_terminal=False)

        manager.render(
            format="list",
            data=[
                {"name": "Item1", "status": "active"},
                {"name": "Item2", "status": "inactive"},
            ],
            schema="eero.items/v1",
            meta={},
        )

        text = output.getvalue()
        assert "Item1" in text
        assert "Item2" in text

    def test_render_table_format(self, manager):
        """Test render in table format."""
        output = StringIO()
        manager.console = Console(file=output, force_terminal=False, width=120)

        manager.render(
            format="table",
            data=[
                {"id": "1", "name": "First"},
                {"id": "2", "name": "Second"},
            ],
            schema="eero.items/v1",
            meta={},
        )

        text = output.getvalue()
        # Table should contain headers derived from keys
        assert "Id" in text or "id" in text.lower()

    def test_format_value_none(self, manager):
        """Test _format_value handles None."""
        result = manager._format_value(None)
        assert "-" in result

    def test_format_value_bool_true(self, manager):
        """Test _format_value handles True."""
        result = manager._format_value(True)
        assert "✓" in result or "green" in result

    def test_format_value_bool_false(self, manager):
        """Test _format_value handles False."""
        result = manager._format_value(False)
        assert "✗" in result or "dim" in result

    def test_format_value_empty_list(self, manager):
        """Test _format_value handles empty list."""
        result = manager._format_value([])
        assert "-" in result

    def test_format_value_list_with_items(self, manager):
        """Test _format_value handles list with items."""
        result = manager._format_value([1, 2, 3])
        assert "3 items" in result

    def test_format_value_dict(self, manager):
        """Test _format_value handles dict."""
        result = manager._format_value({"key": "value"})
        assert "..." in result

    def test_format_value_enum_like(self, manager):
        """Test _format_value handles enum-like strings."""
        result = manager._format_value("EeroNetworkStatus.ONLINE")
        assert result == "online"

    def test_format_value_plain_string(self, manager):
        """Test _format_value passes through plain strings."""
        result = manager._format_value("hello world")
        assert result == "hello world"

    def test_get_columns_for_schema_network(self, manager):
        """Test column selection for network schema."""
        columns = manager._get_columns_for_schema(
            "eero.network.list/v1",
            ["id", "name", "status", "public_ip", "isp_name", "extra"],
        )

        # Should return configured columns that exist in data
        assert "id" in columns
        assert "name" in columns
        assert "status" in columns

    def test_get_columns_for_schema_unknown(self, manager):
        """Test column selection for unknown schema falls back."""
        columns = manager._get_columns_for_schema(
            "unknown.schema/v1",
            ["a", "b", "c", "d", "e", "f", "g", "h"],
        )

        # Should return first 6 columns
        assert len(columns) == 6


# ========================== Column Definitions Tests ==========================


class TestColumnDefinitions:
    """Tests for predefined column configurations."""

    def test_network_table_columns_structure(self):
        """Test NETWORK_TABLE_COLUMNS has correct structure."""
        assert len(NETWORK_TABLE_COLUMNS) > 0
        for col in NETWORK_TABLE_COLUMNS:
            assert "name" in col

    def test_eero_table_columns_structure(self):
        """Test EERO_TABLE_COLUMNS has correct structure."""
        assert len(EERO_TABLE_COLUMNS) > 0
        for col in EERO_TABLE_COLUMNS:
            assert "name" in col

    def test_client_table_columns_structure(self):
        """Test CLIENT_TABLE_COLUMNS has correct structure."""
        assert len(CLIENT_TABLE_COLUMNS) > 0
        for col in CLIENT_TABLE_COLUMNS:
            assert "name" in col

    def test_profile_table_columns_structure(self):
        """Test PROFILE_TABLE_COLUMNS has correct structure."""
        assert len(PROFILE_TABLE_COLUMNS) > 0
        for col in PROFILE_TABLE_COLUMNS:
            assert "name" in col


# ========================== get_renderer Tests ==========================


class TestGetRenderer:
    """Tests for get_renderer helper function."""

    def test_returns_renderer_from_context(self):
        """Test get_renderer returns renderer from context object."""
        mock_ctx = MagicMock()
        mock_ctx.obj = MagicMock()
        mock_ctx.obj.output_ctx = OutputContext(format=OutputFormat.JSON)

        renderer = get_renderer(mock_ctx)

        assert isinstance(renderer, OutputRenderer)
        assert renderer.ctx.format == OutputFormat.JSON

    def test_creates_default_when_no_context(self):
        """Test get_renderer creates default when no context."""
        mock_ctx = MagicMock()
        mock_ctx.obj = None

        renderer = get_renderer(mock_ctx)

        assert isinstance(renderer, OutputRenderer)
        assert renderer.ctx.format == OutputFormat.TABLE  # Default
